apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
spec:
  selector:
    matchLabels:
      app: app01
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: app01
        image: nginx
        ports:
        - containerPort: 80
